config/routes.rb
Rails.application.routes.draw do

	get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
 
    resources :sessions, only: [:create, :destroy]
    resource :home, only: [:show]
 
    root to: "home#index"


 	get 'sessions/create'

  	get 'sessions/destroy'

    get 'game', to: 'game#view'

	get 'user', to: 'user#view', as: :user

    get 'badges', to: 'user#badges'

    get 'profile', to: 'user#profile'

    get 'mygames', to: 'user#view'

	post 'create_user', to: 'user#create', as: :create_user
	post 'create_game', to: 'game#create', as: :create_game
    post 'play_game', to: 'game#play', as: :play_game
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
# == Schema Information
#
# Table name: badges
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  wins       :integer          default(0)
#  user_id    :integer
#  losses     :integer          default(0)
#  wstreak    :integer          default(0)
#  lstreak    :integer          default(0)
#

class Badge < ActiveRecord::Base
	belongs_to :user, class_name: "User"
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  status      :string           default("Player 1’s turn")
#  matrix      :string           default("[[0, 0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0, 0]]")
#  user_1_id   :integer
#  user_2_id   :integer
#  curr_player :integer          default(1)
#  winner      :string
#

class Game < ActiveRecord::Base
	belongs_to :user_1, class_name: "User"
	belongs_to :user_2, class_name: "User"

	def play(col)
		matrix = eval(self.matrix)
		# set the current piece
		for i in 0..5
			k = 5 - i
			if matrix[k][col] == 0
				matrix[k][col] = self.curr_player
				break
			end
		end

		update! matrix: matrix

		if win?(self.curr_player)
			update! winner: self.curr_player == 1 ? user_1.name : user_2.name
			if self.curr_player == 1
				victory(user_1)
				defeat(user_2)	
			else
				victory(user_2)
				defeat(user_1)
			end
		else
			# toggle between 1 and 2
			update! curr_player: 3 - self.curr_player
		end
	end

	def victory(player)
		if Badge.exists?(user: player)
			badge = Badge.where(user: player).first
			badge.wins = badge.wins + 1
			badge.wstreak = badge.wstreak + 1
			badge.lstreak = 0
			badge.save!
		else
			new_badge = Badge.new(user: player)
			new_badge.wins = new_badge.wins + 1
			new_badge.wstreak = new_badge.wstreak + 1
			new_badge.lstreak = 0
			new_badge.save!
		end
	end

	def defeat(player)
		if Badge.exists?(user: player)
			badge = Badge.where(user: player).first
			badge.losses = badge.losses + 1
			badge.wstreak = 0
			badge.lstreak = badge.lstreak + 1
			badge.save!
		else
			new_badge = Badge.new(user: player)
			new_badge.losses = new_badge.losses + 1
			new_badge.wstreak = 0
			new_badge.lstreak = new_badge.lstreak + 1
			new_badge.save!
		end
	end

	def win?(player)
		matrix = eval(self.matrix)
		check = Array.new(6){Array.new(7, 0)}
		num = player

		#check for horizontal wins
		for row in 0..5
			for col in 0..3
				if matrix[row][col] == num and matrix[row][col+1] == num and matrix[row][col+2] == num and matrix[row][col+3] == num
					return true
				end
			end
		end

		#check for vertical wins
		for col in 0..6
			for row in 0..2
				if matrix[row][col] == num and matrix[row+1][col] == num and matrix[row+2][col] == num and matrix[row+3][col] == num
					return true
				end
			end
		end

		#check for \ wins 
		for row in 0..2
			for col in 0..3
				if matrix[row][col] == num and matrix[row+1][col+1] == num and matrix[row+2][col+2] == num and matrix[row+3][col+3] == num
					return true
				end
			end
		end			

		#check for / wins
		for row in 3..5
			for col in 0..3
				if matrix[row][col] == num and matrix[row-1][col+1] == num and matrix[row-2][col+2] == num and matrix[row-3][col+3] == num
					return true
				end
			end
		end	

		return false

	end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  provider         :string
#  uid              :string
#  name             :string
#  oauth_token      :string
#  oauth_expires_at :datetime
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  wins             :integer          default(0)
#

require 'koala'

class User < ActiveRecord::Base
	has_many :games

	def self.from_omniauth(auth)
		graph = Koala::Facebook::API.new(auth.credentials.token)
    	friends = graph.get_connections("me", "friends")

   		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    	user.provider = auth.provider
	    	user.uid = auth.uid
	    	user.name = auth.info.name
	    	user.oauth_token = auth.credentials.token
	    	user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    	user.save!
    	end	
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
	def create
		user1 = User.where(name: params[:user1]).first

		if User.exists?(name: params[:user2])
			user2 = User.where(name: params[:user2]).first
		else
			user2 = User.create(name: params[:user2])
		end

		game = Game.new(user_1: user1, user_2: user2)
		game.save!

		redirect_to user_path(user: user1)
	end

	def view
		@curr_user ||= User.find(session[:user_id]) if session[:user_id]
		@config = {
			1 => "yel",
			2 => "red",
			0 => "nan"
		}
		@game_id = params[:game]
		game = Game.find(@game_id)
		@user1 = User.find(game.user_1).name
		@user2 = User.find(game.user_2).name
		@curr_player = game.curr_player
		@board = eval(game.matrix)
		@can_move = game.curr_player == 1 && @curr_user.name == @user1 ||
					game.curr_player == 2 && @curr_user.name == @user2
		@winner = game.winner
	end

	def play
		game = Game.find(params[:game])
		col = params[:column].to_i
		game.play(col)

		redirect_to game_path(game: params[:game])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		@users = User.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end
 
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def create
		name = params[:name]
		new_user = User.new(name: name)
		new_user.save!
		new_badge = Badge.new(user: new_user)
		new_badge.save!
		
		redirect_to '/'
	end

	def view
		@curr_user ||= User.find(session[:user_id]) if session[:user_id]
		@games = Game.where(user_1: @curr_user).or(Game.where(user_2: @curr_user))

		fb_token = @curr_user.oauth_token
		graph = Koala::Facebook::API.new(fb_token)
		@friends = graph.get_connections("me", "friends")
	end

	def badges
		@curr_user ||= User.find(session[:user_id]) if session[:user_id]
		@curr_badge = Badge.where(user: @curr_user).first
		@no_badge = false
		@three_win = false
		@five_win = false
		@three_loss = false
		if @curr_badge.nil?
			@no_badge = true
		else
			if @curr_badge.wstreak >= 3
				@three_win = true
			end
			if @curr_badge.wstreak >= 5
				@five_win = true
			end
			if @curr_badge.lstreak >= 3
				@three_loss = true
			end
			if !@three_win and !@five_win and !@three_loss 
				@no_badge = true
			end
		end
	end

	def profile
		@curr_user ||= User.find(session[:user_id]) if session[:user_id]
		@curr_badge = Badge.where(user: @curr_user).first
		if @curr_badge.nil?
			@wins = 0
			@losses = 0
			@ratio = 0
			@total = 0
		else
			@wins = @curr_badge.wins
			@losses = @curr_badge.losses
			@ratio = @wins.to_f / (@wins + @losses)
			@total = @wins + @losses
		end

   		@image = "http://graph.facebook.com/#{@curr_user.uid}/picture?type=large"

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/game/view.html.erb
<div id = "container" style = "overflow: hidden; width: 100%">
	<div id="inner" style = "overflow: hidden; ">
		
		
</div>

<div class="game__text" id="game__title">
			<%= @user1 %> vs <%= @user2 %>
		</div>

<% if !@winner.nil? %>
	<div class="game__text" id="game__status--win">
		<%= @winner %> wins!
		<%= link_to "Click here to claim your prize!", image_path('https://www.youtube.com/watch?v=NRSKZmJLnJ0') %>
	</div>
<% else %>
	<div class="game__text" id="game__status--curr">
		Player <%= @curr_player %>’s turn
	</div>
<% end %>

<br> 
<br>
<div class = "board">
<table id="game__board">
	<% for i in 0..5 %>
	<tr>
		
		<% for j in 0..6 %>
			<td> <div class= <%= @config[@board[i][j]] %>  > </div></td>
		<% end %>	


	</tr>
	<% end %>
</table>
</div>
<br/><br/>

<div class = "gameplay">
<% if @winner.nil? %>
	<%= form_tag play_game_path do %>
	  <%= label_tag :column, "Enter column number (from 0 to 6)" %>
	  <%= text_area_tag :column, nil, :maxlength => 1, :size => 40 %>
	  <%= hidden_field_tag :game, @game_id %>
	  <%= submit_tag "Play!", :class => 'gamebutton' %>
	<% end %>
<% end %>

</div>

app/views/home/index.html.erb
<h2 class = "home-header">
	<% if current_user %>
        ~ Welcome <strong><%= current_user.name %></strong>! ~
      <% else %>
        ~ Register your account through facebook! ~
      <% end %>
</h2>

<!-- <h2 class = "home-header">
<%= form_tag create_user_path do %>
  <%= label_tag :name, "Your Name here!" %>
  <%= text_area_tag :name, nil, :placeholder => 'ex: Warren Shen', :maxlength => 25, :size => 40 %>
  <%= submit_tag "Create user", :class => 'button' %>
<% end %>
</h2>
 -->

<div id="container" style="background-color:orange;overflow:hidden;width:100%; opacity: 0.4;">
  <div id="inner" style="overflow:hidden;width: 2000px">
     <div style="float:left;background-color:blue;width:50px;height:50px; opacity: 1.0;">
     </div>
     <div style="float:left;background-color:green;width:100px;height:50px; opacity: 0.7;">
     </div>
     <div style="float:left;background-color:red;width:50px;height:50px; opacity: 0.5;">
     </div>
     
  </div>
</div>

<br>

<div id = "container" style = "overflow: hidden; width: 100%">
  <div id="inner" style = "overflow: hidden; width: 2000px">
		<div class = "usersbox" style = "float:left; width: 300px; height: 300px">

			<div class = "usertitle">
			<h3 id = "list"> FB USERS </h3>
			</div>

			<br>
			<hr style = "width: 150px;">

			<div class = "users">
			<% @users.each do |user| %>

				<!-- verify fb user -->
				<% if !user.uid.nil? %>
					<h3> <%= link_to user.name, user_path(user: user), :class => 'userb' %> </h3> 
				<% end %>
				
			<% end %>
			</div>

			</br>

		</div>

		<div class = "description">
			<h1 class = "projecttitle"> ConnectFour - Ruby on Rails </h1>

			<hr style = "width: 500px;">
			</br>

			Hey, so this is our Ruby on Rails Project :D </br>
			We made a connect four game. We had a lot of fun making the web app and  </br> 
			I hope you guys can have a lot of fun playing around and interacting with our connect four games! </br> 

			<h1> ⤴︎ ε=ε=(ง ˃̶͈̀ᗨ˂̶͈́)۶ ⤴︎ </h1> 

			Melissa Ly | Nanxi Wang | Tina Zheng | Casey Takeda | Justin Ma


		</div>

	</div>
</div>


<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Connect Four</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>

  <div class = "sign">
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign Out", signout_path, id: "sign_out", :class => 'signo' %>
      <% else %>
        <%= link_to "Sign In With Facebook", "/auth/facebook?scope=user_friends", id: "sign_in", :class => 'signb'%>
      <% end %>
  </div> 

  <% if current_user %>
  <ul>
    <li>
      <a class = "navlink" href ="/mygames" style = "color: orange;"> Current Games </a>
    </li>

    <li>
      <a class = "navlink" href = "/badges" style = "color: red;"> My Badges </a>
    </li>

    <li>
      <a class = "navlink" href ="/profile" style = "color: green;"> My Profile </a>
    </li>
    <li>
      <a class = "navlink" href ="/"> Home </a>
    </li>
  </ul>

  <% else %>
  <ul>
    <li>
      <a class = "navlink3" href ="https://github.com/tinazheng/connectfour" target="_blank">  ᕕ( ᐛ )ᕗ </a>
    </li>
    <li> 
      <a class = "navlinktina" href ="https://www.facebook.com/tinazheng?fref=ts" target="_blank"> o(^▽^)o </a> 
    </li>
    <li> 
      <a class = "navlinkmelissa" href ="https://www.facebook.com/profile.php?id=100000090248103&fref=ts" target="_blank"> o(^▽^)o </a> 
    </li>
    <li> 
      <a class = "navlinkjustin" href ="https://www.facebook.com/justin.ma.5?fref=ts" target="_blank"> o(^▽^)o </a> 
    </li>
    <li> 
      <a class = "navlinknanxi" href ="https://www.facebook.com/ixnanxi?fref=ts" target="_blank"> o(^▽^)o </a> 
    </li>
    <li> 
      <a class = "navlinkcasey" href ="https://www.facebook.com/CaseTakeda?fref=ts" target="_blank"> o(^▽^)o </a> 
    </li>
  </ul>
  <% end %>

</nav>
<%= yield %>
 
 <div id="background"></div>

</body>
</html>

app/views/user/badges.html.erb
<h1 class = "title" style = "color: red; opacity: 0.7;"> ~ <%= @curr_user.name %>'s Badges ~ </h1>
<div id = "container" style = "overflow: hidden; width: 100%; opacity: 0.5;">

 	<div class="badges" style = "overflow: hidden; ">

 		<% if @no_badge %>
 			<h1 style = "color: orange;"> YOU HAVE NO BADGES </h1>
 		<% else %>
 			<% if @three_win %>
 				<h1 style = "color: blue;"> YOU ARE ON A THREE WIN STREAK </h1> <br>
 			<% end %>

 			<% if @five_win %>
 				<h1 style = "color: green;"> YOU ARE ON A FIVE WIN STREAK </h1> <br> 
 			<% end %>
 			<% if @three_loss %>
 				<h1 style = "color: red;"> YOU ARE ON A THREE LOSS STREAK </h1>
 			<% end %>
 		<% end %>
				
		
	</div>
</div>

app/views/user/profile.html.erb
<h1 class = "title" style = "color: green; opacity: 0.7;"> ~ <%= @curr_user.name %>'s Profile ~ </h1>

<div id = "container" style = "overflow: hidden; width: 100%;">
  <div class="fun" style = "overflow: hidden; color: green; opacity: 0.7;">

	<%= image_tag(@image, :alt => "rss feed", :class => 'profilepic') %>
	
	<div class = "stats">
		<h3 class = "name"> <%= @curr_user.name %> </h3>
		<hr>  
		Wins: <%= @wins %> </br>
		Loses: <%= @losses %></br>
		W/L Ratio: <%= @ratio %> </br>
		Number of Games Played: <%= @total %>
	</div>

  </div>
</div>

app/views/user/view.html.erb
<h1 class = "title" style = "color: orange;"> ~ Welcome to Connect Four! ~ </h1>
<div id = "container" style = "overflow: hidden; width: 100%">

 	<div class="fun" style = "overflow: hidden; ">

 		<div style = "float:left; width: 500px; height: 500px; overflow-y: scroll; margin-left: 40px;">

	 		<h2 class = "current_games" style = "color: #42C0FB;"> Current Games </h2>
			
			<hr style = "width: 500px;">

			<% if !@games.nil? %>
				<% @games.each do |game| %>
					<%= link_to game.user_1.name + " vs " + game.user_2.name, game_path(game: game), :class => 'curr_games1' %>
					<br/>
				<% end %>
			<% else %>
				<h2 class = "no_games"> You don't have any current games right now! </h2>
			<% end %>

		</div>

		<div class="verticalLine" style = "border-left: thick dashed blue; float: left; height: 500px; opacity: 0.3; margin-left: 58px;"> </div>

		<h2 style = "color: green;"> Start a Game With </h2>

		<hr style = "width: 500px;">

		<div style = "overflow-y: scroll;">
		<% @friends.each do |friend| %>
			<%= link_to friend["name"], create_game_path(user1: @curr_user.name, user2: friend["name"]), :class => 'curr_games2', method: :post %> <br/>
		<% end %>
		</div>

		<br />
		<%= form_tag create_game_path do %>
		  <% label_tag :user1, @curr_user.name %>
		  <% text_area_tag :user1 %>
		  <%= label_tag :user2, "Enter Opponent's Name Here" %> </br>
		  <%= text_area_tag :user2, nil, :placeholder => 'ex: Warren Shen', :maxlength => 22, :size => 40 %> <br />
		  <%= submit_tag "Create game!", :class => 'opponentbutton' %>
		<% end %>

		<br />

	</div>
</div>
<br>
<br>